services:
  stockflowenterprise:
    image: stockflowenterprise
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "${STOCKFLOW_HOST_PORT:-3000}:80"
